import {
  IoAdd, IoAddCircle, IoAddCircleOutline, IoAirplaneOutline, IoAlarm, IoAlarmOutline, IoAlbumsOutline,
  IoAlertCircle, IoAlertCircleOutline, IoAnalyticsOutline, IoArchiveOutline, IoArrowDownCircleOutline,
  IoArrowUndoOutline, IoArrowUpCircle, IoArrowUpCircleOutline, IoAttachOutline, IoBarbellOutline,
  IoBatteryDeadOutline, IoBatteryFullOutline, IoBatteryHalfOutline, IoBookOutline, IoBookmark,
  IoBookmarkOutline, IoBriefcase, IoBriefcaseOutline, IoBusinessOutline, IoCafeOutline, IoCalendarOutline,
  IoCardOutline, IoCashOutline, IoCheckboxOutline, IoCheckmark, IoCheckmarkCircle, IoCheckmarkCircleOutline,
  IoCheckmarkDone, IoCheckmarkDoneCircleOutline, IoCheckmarkDoneOutline, IoChevronBack,
  IoChevronBackCircleOutline, IoChevronDown, IoChevronForward, IoChevronForwardCircleOutline, IoChevronUp,
  IoClipboardOutline, IoClose, IoCloseCircle, IoCloseCircleOutline, IoCloudOutline, IoCodeSlashOutline,
  IoCopyOutline, IoCreateOutline, IoDocumentOutline, IoDocumentText, IoDocumentTextOutline, IoEllipse,
  IoEllipseOutline, IoEllipsisHorizontal, IoEllipsisHorizontalCircleOutline, IoEllipsisHorizontalOutline,
  IoExitOutline, IoExpandOutline, IoEyeOutline, IoFileTrayOutline, IoFilter, IoFitnessOutline, IoFlag,
  IoFlagOutline, IoFlame, IoFlameOutline, IoFlashOutline, IoFlower, IoFolderOutline, IoGiftOutline,
  IoGitCommitOutline, IoGlobeOutline, IoGridOutline, IoHandLeftOutline, IoHeart, IoHeartOutline,
  IoHomeOutline, IoHourglassOutline, IoImagesOutline, IoInformationCircleOutline, IoLeafOutline,
  IoLibraryOutline, IoLinkOutline, IoListOutline, IoLockClosedOutline, IoLogoGithub, IoMapOutline,
  IoMedicalOutline, IoMedkitOutline, IoMenuOutline, IoMicOutline, IoMoonOutline, IoMoveOutline,
  IoMusicalNotesOutline, IoNotificationsOffOutline, IoNotificationsOutline, IoPartlySunnyOutline,
  IoPauseCircleOutline, IoPeopleCircleOutline, IoPeopleOutline, IoPersonCircleOutline, IoPersonOutline,
  IoPieChartOutline, IoPricetagOutline, IoRadioOutline, IoRainyOutline, IoReceiptOutline, IoRefreshOutline,
  IoRemove, IoReorderFourOutline, IoReorderTwoOutline, IoRepeat, IoRepeatOutline, IoReturnDownForwardOutline,
  IoReturnUpBackOutline, IoRibbonOutline, IoSchoolOutline, IoSearch, IoSearchOutline, IoSettingsOutline,
  IoShareOutline, IoSnowOutline, IoSquareOutline, IoStatsChartOutline, IoStopwatchOutline, IoSunnyOutline,
  IoSwapHorizontalOutline, IoSwapVertical, IoSyncOutline, IoTelescopeOutline, IoText, IoTextOutline,
  IoTimeOutline, IoTimerOutline, IoTodayOutline, IoToggleOutline, IoTrash, IoTrashOutline,
  IoTrendingDownOutline, IoTrendingUp, IoTrendingUpOutline, IoTrophyOutline, IoWallet, IoWalletOutline,
  IoWater, IoWaterOutline, IoMic, IoCheckbox, IoArrowDown, IoArrowUp, IoHelpCircleOutline,
  IoStar, IoStarOutline, IoFlash, IoThunderstorm, IoLockClosed, IoSparklesOutline,
  IoCallOutline, IoCarOutline, IoCartOutline, IoGitNetworkOutline, IoHappyOutline,
  IoPawOutline, IoPerson, IoPersonAddOutline, IoPin, IoShieldCheckmarkOutline,
  IoShieldOutline, IoWalkOutline,
  IoBulbOutline, IoCloudUploadOutline, IoDownloadOutline, IoEarthOutline, IoFlaskOutline,
  IoFolderOpenOutline, IoGitBranchOutline, IoHammerOutline, IoLockOpenOutline, IoPinOutline,
  IoScanOutline, IoServerOutline, IoShareSocialOutline,
  IoAppsOutline, IoCalculatorOutline, IoFilterOutline,
} from 'react-icons/io5';

// Every Ionicons name actually used across the app, explicitly named-
// imported (not `import * as Io5`) so bundlers can tree-shake the ~1300
// icons this app doesn't use instead of shipping the entire icon set in
// the main chunk. Regenerate this list (see webapp/extract_icons.cjs) if a
// new `<Icon name="...">` or `icon: '...'` constant is introduced.
const ICONS = {
  add: IoAdd, 'add-circle': IoAddCircle, 'add-circle-outline': IoAddCircleOutline,
  'airplane-outline': IoAirplaneOutline, alarm: IoAlarm, 'alarm-outline': IoAlarmOutline,
  'albums-outline': IoAlbumsOutline, 'alert-circle': IoAlertCircle, 'alert-circle-outline': IoAlertCircleOutline,
  'analytics-outline': IoAnalyticsOutline, 'archive-outline': IoArchiveOutline,
  'arrow-down-circle-outline': IoArrowDownCircleOutline, 'arrow-undo-outline': IoArrowUndoOutline,
  'arrow-up-circle': IoArrowUpCircle, 'arrow-up-circle-outline': IoArrowUpCircleOutline,
  'attach-outline': IoAttachOutline, 'barbell-outline': IoBarbellOutline,
  'battery-dead-outline': IoBatteryDeadOutline, 'battery-full-outline': IoBatteryFullOutline,
  'battery-half-outline': IoBatteryHalfOutline, 'book-outline': IoBookOutline, bookmark: IoBookmark,
  'bookmark-outline': IoBookmarkOutline, briefcase: IoBriefcase, 'briefcase-outline': IoBriefcaseOutline,
  'business-outline': IoBusinessOutline, 'cafe-outline': IoCafeOutline, 'calendar-outline': IoCalendarOutline,
  'card-outline': IoCardOutline, 'cash-outline': IoCashOutline, 'checkbox-outline': IoCheckboxOutline,
  checkmark: IoCheckmark, 'checkmark-circle': IoCheckmarkCircle,
  'checkmark-circle-outline': IoCheckmarkCircleOutline, 'checkmark-done': IoCheckmarkDone,
  'checkmark-done-circle-outline': IoCheckmarkDoneCircleOutline,
  'checkmark-done-outline': IoCheckmarkDoneOutline, 'chevron-back': IoChevronBack,
  'chevron-back-circle-outline': IoChevronBackCircleOutline, 'chevron-down': IoChevronDown,
  'chevron-forward': IoChevronForward, 'chevron-forward-circle-outline': IoChevronForwardCircleOutline,
  'chevron-up': IoChevronUp, 'clipboard-outline': IoClipboardOutline, close: IoClose,
  'close-circle': IoCloseCircle, 'close-circle-outline': IoCloseCircleOutline, 'cloud-outline': IoCloudOutline,
  'code-slash-outline': IoCodeSlashOutline, 'copy-outline': IoCopyOutline, 'create-outline': IoCreateOutline,
  'document-outline': IoDocumentOutline, 'document-text': IoDocumentText,
  'document-text-outline': IoDocumentTextOutline, ellipse: IoEllipse, 'ellipse-outline': IoEllipseOutline,
  'ellipsis-horizontal': IoEllipsisHorizontal,
  'ellipsis-horizontal-circle-outline': IoEllipsisHorizontalCircleOutline,
  'ellipsis-horizontal-outline': IoEllipsisHorizontalOutline, 'exit-outline': IoExitOutline,
  'expand-outline': IoExpandOutline, 'eye-outline': IoEyeOutline, 'file-tray-outline': IoFileTrayOutline,
  filter: IoFilter, 'fitness-outline': IoFitnessOutline, flag: IoFlag, 'flag-outline': IoFlagOutline,
  flame: IoFlame, 'flame-outline': IoFlameOutline, 'flash-outline': IoFlashOutline, flower: IoFlower,
  'folder-outline': IoFolderOutline, 'gift-outline': IoGiftOutline, 'git-commit-outline': IoGitCommitOutline,
  'globe-outline': IoGlobeOutline, 'grid-outline': IoGridOutline, 'hand-left-outline': IoHandLeftOutline,
  heart: IoHeart, 'heart-outline': IoHeartOutline, 'home-outline': IoHomeOutline,
  'hourglass-outline': IoHourglassOutline, 'images-outline': IoImagesOutline,
  'information-circle-outline': IoInformationCircleOutline, 'leaf-outline': IoLeafOutline,
  'library-outline': IoLibraryOutline, 'link-outline': IoLinkOutline, 'list-outline': IoListOutline,
  'lock-closed-outline': IoLockClosedOutline, 'logo-github': IoLogoGithub, 'map-outline': IoMapOutline,
  'medical-outline': IoMedicalOutline, 'medkit-outline': IoMedkitOutline, 'menu-outline': IoMenuOutline,
  'mic-outline': IoMicOutline, 'moon-outline': IoMoonOutline, 'move-outline': IoMoveOutline,
  'musical-notes-outline': IoMusicalNotesOutline, 'notifications-off-outline': IoNotificationsOffOutline,
  'notifications-outline': IoNotificationsOutline, 'partly-sunny-outline': IoPartlySunnyOutline,
  'pause-circle-outline': IoPauseCircleOutline, 'people-circle-outline': IoPeopleCircleOutline,
  'people-outline': IoPeopleOutline, 'person-circle-outline': IoPersonCircleOutline,
  'person-outline': IoPersonOutline, 'pie-chart-outline': IoPieChartOutline,
  'pricetag-outline': IoPricetagOutline, 'radio-outline': IoRadioOutline, 'rainy-outline': IoRainyOutline,
  'receipt-outline': IoReceiptOutline, 'refresh-outline': IoRefreshOutline, remove: IoRemove,
  'reorder-four-outline': IoReorderFourOutline, 'reorder-two-outline': IoReorderTwoOutline, repeat: IoRepeat,
  'repeat-outline': IoRepeatOutline, 'return-down-forward-outline': IoReturnDownForwardOutline,
  'return-up-back-outline': IoReturnUpBackOutline, 'ribbon-outline': IoRibbonOutline,
  'school-outline': IoSchoolOutline, search: IoSearch, 'search-outline': IoSearchOutline,
  'settings-outline': IoSettingsOutline, 'share-outline': IoShareOutline, 'snow-outline': IoSnowOutline,
  'square-outline': IoSquareOutline, 'stats-chart-outline': IoStatsChartOutline,
  'stopwatch-outline': IoStopwatchOutline, 'sunny-outline': IoSunnyOutline,
  'swap-horizontal-outline': IoSwapHorizontalOutline, 'swap-vertical': IoSwapVertical,
  'sync-outline': IoSyncOutline, 'telescope-outline': IoTelescopeOutline, text: IoText,
  'text-outline': IoTextOutline, 'time-outline': IoTimeOutline, 'timer-outline': IoTimerOutline,
  'today-outline': IoTodayOutline, 'toggle-outline': IoToggleOutline, trash: IoTrash,
  'trash-outline': IoTrashOutline, 'trending-down-outline': IoTrendingDownOutline,
  'trending-up': IoTrendingUp, 'trending-up-outline': IoTrendingUpOutline, 'trophy-outline': IoTrophyOutline,
  wallet: IoWallet, 'wallet-outline': IoWalletOutline, water: IoWater, 'water-outline': IoWaterOutline,
  mic: IoMic, checkbox: IoCheckbox, 'arrow-down': IoArrowDown, 'arrow-up': IoArrowUp,
  star: IoStar, 'star-outline': IoStarOutline, flash: IoFlash, thunderstorm: IoThunderstorm,
  'lock-closed': IoLockClosed, 'sparkles-outline': IoSparklesOutline,
  'call-outline': IoCallOutline, 'car-outline': IoCarOutline, 'cart-outline': IoCartOutline,
  'git-network-outline': IoGitNetworkOutline, 'happy-outline': IoHappyOutline, 'paw-outline': IoPawOutline,
  person: IoPerson, 'person-add-outline': IoPersonAddOutline, pin: IoPin,
  'shield-checkmark-outline': IoShieldCheckmarkOutline, 'shield-outline': IoShieldOutline,
  'walk-outline': IoWalkOutline,
  'bulb-outline': IoBulbOutline, 'cloud-upload-outline': IoCloudUploadOutline,
  'download-outline': IoDownloadOutline, 'earth-outline': IoEarthOutline, 'flask-outline': IoFlaskOutline,
  'folder-open-outline': IoFolderOpenOutline, 'git-branch-outline': IoGitBranchOutline,
  'hammer-outline': IoHammerOutline, 'lock-open-outline': IoLockOpenOutline, 'pin-outline': IoPinOutline,
  'scan-outline': IoScanOutline, 'server-outline': IoServerOutline, 'share-social-outline': IoShareSocialOutline,
  'apps-outline': IoAppsOutline, 'calculator-outline': IoCalculatorOutline, 'filter-outline': IoFilterOutline,
};

export function Icon({ name, size = 20, color, className, style }) {
  const Component = ICONS[name] ?? IoHelpCircleOutline;
  return <Component size={size} color={color} className={className} style={style} aria-hidden="true" focusable="false" />;
}
